name: Publish
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'jamsch/expo-speech-recognition' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: "npm"

      - run: npm ci
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1.8.0
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
