name: Run Typescript

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  typescript-check:
    name: Typescript check
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Run Typescript check
        run: npm run ts:check
